server:
  port: 9091
  context-path: /
  session:
    timeout: 300
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true

logging:
  config: classpath:config/logback.xml

spring:
  application:
    name: app-user

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true



