server:
  port: 8040
  context-path: /
  session:
    timeout: 300
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true

spring:
  application:
    name: infra-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true


zuul:
  ignored-services: '*'
  routes:
    app-order:
      service-id: app-order
      path: /order/**
      sensitive-headers: xxx,xx
  prefix: /api
  sensitive-headers:
  ignore-security-headers: false
  InfraPreZuulFilter:
    pre:
      disable: true




