server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/William750214/projconfig
          search-paths:
          username:
          password:
      label: master
  rabbitmq:
    host: 10.0.1.110
    port: 5672
    username: guest
    password: guest
  application:
    name: infra-config

encrypt:
  key-store:
    alias: jwt
    location: classpath:/jwt.jks
    secret: 123456
    password: 123456

security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin123

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true





